Input group
cecton/yewprint pull request #68
Opened 2020-11-05 16:53 UTC by Yozhgoor

Making the component of the input group

Blueprint-doc: https://blueprintjs.com/docs/#core/components/text-inputs.input-group
Code: https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/inputGroupExample.tsx

2020-11-08 08:25 UTC, cecton commented on yewprint/src/control_group.rs
> +            </div>
The only thing you need now is the children. You can take inspiration from [there](https://github.com/cecton/yewprint/blob/main/yewprint/src/buttons.rs#L71)

2020-11-08 08:27 UTC, cecton commented on yewprint/src/input_group.rs
> +                )
You can compare to blueprint [here](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/inputGroup.tsx#L122-L128). You're still missing a few classes

2020-11-08 08:29 UTC, cecton commented on yewprint/src/input_group.rs
> +    pub lefticon: Option<IconName>,
`left_icon`

2020-11-08 08:30 UTC, cecton commented on yewprint/src/input_group.rs
> +                }
There is also a `left_element` which you can declare as `Option<VNode>`. See [here](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/inputGroup.tsx#L178-L180)

2020-11-08 08:31 UTC, cecton commented on yewprint/src/input_group.rs
> +            </div>
Don't forget the right side: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/inputGroup.tsx#L151

2020-11-23 16:33 UTC, Yozhgoor commented
When i try to add another inputgroup i have this error
```
error: only one root html element is allowed (hint: you can wrap multiple html elements in a fragment `<></>`)
```
need some help for that and a review of the actual inputgroup to see how we can fix the difference between yewprint inputgroup and blueprint

2020-11-28 12:26 UTC, Yozhgoor commented
i think it's not perfect but good enough for now
i need more component to make it looking great
what do you think about the actual work @cecton ?

2020-11-28 14:06 UTC, cecton requested changes
It's already nice. Close to be released!

2020-11-28 14:06 UTC, cecton commented on yewprint-doc/src/input_group/mod.rs
> +                placeholder: String::from(""),
Not used (so can be removed)

2020-11-28 14:06 UTC, cecton commented on yewprint/src/buttons.rs
>      pub children: html::Children,
Try with Option

2020-11-28 17:44 UTC, Yozhgoor commented
you review is now reviewed, i still have an issue with the fill props of the control group

but all of your comment is fixed

2020-11-29 10:00 UTC, cecton commented on yewprint-doc/src/control_group/example.rs
> +                        (Some(Sorting::PriceDescending), "Price-descending".to_string()),
Labels are still not the same than blueprint's doc

2020-11-29 10:00 UTC, cecton requested changes
ControlGroup: Vertical+Fill doesn't behave the same in the example on blueprint. Other than that it looks good

InputGroup: various work to do

2020-11-30 17:29 UTC, Yozhgoor commented
For now i have some issues: 

inputGroup is visually bad, i don't know how to easily make a better render
i can't use the select for the last inputGroup, bad render with small and round props. Maybe use a menu like Blueprint
i can't use tag for now, bad render with small prop. Need to search to know what to put inside the tag

ControlGroup fill prop don't work

2020-12-01 11:18 UTC, Yozhgoor commented
Need a review @cecton :D  
ControlGroup is fine i think
InputGroup need more enhancements but i think we can push it for now and come back on it later with some other component (like popover) not implemented yet

2020-12-03 12:26 UTC, cecton approved these changes
:ok_hand:

2020-12-03 12:26 UTC, merged