Slider
cecton/yewprint pull request #95
Opened 2021-03-10 01:04 UTC by yozhgoor

closes #94

2021-03-24 15:42 UTC, cecton commented on yewprint/src/slider.rs
> +    pub label_step_size: Option<usize>,
You should keep your type: `u32`.

I know you have casting issue but then you need to cast it

2021-03-24 15:43 UTC, cecton commented on yewprint/src/slider.rs
> +        let label_values = if self.props.label_values.is_some() {
geez you forgot how to `if let`? :disappointed:

2021-03-25 17:27 UTC, yozhgoor commented
todo! {

- [ ] label renderer 

- [ ] example with label renderer

- [ ] prevent page scroll on arrows key use

- [ ] click on track move the handle to the place clicked

}

2021-03-31 12:48 UTC, cecton commented on yewprint-doc/src/slider/example.rs
> +#[derive(Debug, Clone, PartialEq)]
You can also implement Copy because the enum is very small in size

2021-03-31 12:48 UTC, cecton commented on yewprint/src/slider.rs
> +                        .clamp(0, self.props.options.len() - 1);
There is nothing below 0. This clamp is useless

2021-03-31 12:48 UTC, cecton commented on yewprint/src/slider.rs
> +                    let (value, _) = self.props.options[index].clone();
Use `Option::get` instead of clamp.

2021-03-31 12:48 UTC, cecton commented on yewprint/src/slider.rs
> +                    / (self.props.options.len() - 1);
lol! Check out `Iterator::enumerate`

2021-03-31 12:52 UTC, cecton commented on yewprint-doc/src/slider/example.rs
> +                        (1.0, String::from("1.0")),
For the sake of the example, please limit de labels to 0.0, 0.5 and 1.0. I don't want to see the others but they need to be there

2021-04-07 09:23 UTC, cecton requested changes

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +                let position = pixel_delta as f64 / self.tick_size.unwrap() as f64;
the `.round()` and usize conversion should probably moved here for clarity sake.

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +    KeyDown(KeyboardEvent),
It seems weird that one receives a u32 and the other a keyboard event. Let's change `Change` to use a mouse event for consistency. We can also rename `Change` to `Mouse` and `KeyDown` to `Keyboard`.

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +    pub options: Vec<(T, Option<String>)>,
This shouldn't have a default value. It doesn't make any sense to render a slider with no options.

Also: what happens if the user provide an empty vec? Does it crash badly? What should happen? Let's think about it

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +    pub value: T,
What does happen if the value is not in the options vec?

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +                        .position(|i| i.0 == self.props.value)
Try use the tuple deconstructor instead

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +                        .position(|i| i.0 == self.props.value)
Also: `i` are for indexes. Usually of type usize or an integer of any type

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +                        .position(|i| i.0 == self.props.value)
(Same comment about number and variable name)

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +            .position(|i| i.0 == self.props.value)
(Same comment about number and variable name)

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +                self.props.onchange.emit(value);
There used to be a check here that made sure the value actually changed before emitting the event. Why did you remove it?

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +        self.tick_size = Some(track_size / (self.props.options.len() - 1) as f64);
This computation is unnecessary here. Move it to the messages for clarity sake. It's not like your computer is going to struggle for doing 2 more arithmetic expressions.

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +                    onkeydown=self.link.callback(Msg::KeyDown)
Use the closure instead. We disabled it clippy lint expressly for that XD

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +                        style=format!("left: 0%; right: {}%; top: 0px;", 100 - percentage)
I don't feel comfortable with the precision here. If someone wants to make a huge slider they will notice the handler will be off because of the lack of precision. Can you try to improve the precision?

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +                )
```suggestion
                onclick=self.link.callback(|event| Msg::Change(event.client_x() as u32))
```

Use type inference

2021-04-07 09:23 UTC, cecton commented on yewprint/src/slider.rs
> +            );
This is atrocious. Did I make this `if_html!`? :confounded: 

Try using map on the option instead.

2021-04-07 09:39 UTC, yozhgoor commented on yewprint/src/slider.rs
> +                )
error[E0282]: type annotations needed

2021-04-07 10:18 UTC, cecton requested changes

2021-04-07 10:18 UTC, cecton commented on yewprint/src/slider.rs
> +                self.tick_size = Some(track_size / (self.props.options.len() - 1) as f64);
Why do you store it in self?

2021-04-07 10:18 UTC, cecton commented on yewprint/src/slider.rs
> +        };
Try to go functional. Use map

2021-04-07 10:18 UTC, cecton commented on yewprint/src/slider.rs
> +                let track_size = self.track_ref.cast::<Element>().unwrap().client_width() as f64;
Re-use the track_ref you just casted already

2021-04-07 11:43 UTC, cecton requested changes

2021-04-07 11:43 UTC, cecton commented on yewprint/src/slider.rs
> +                        .position(|(v, _)| *v == self.props.value)
just call it value XD

2021-04-07 11:43 UTC, cecton commented on yewprint/src/slider.rs
> +                let position = position.round() as usize;
Write this in one line.

2021-04-07 11:43 UTC, cecton commented on yewprint/src/slider.rs
> +                    position.saturating_sub(track_rect.get_bounding_client_rect().left() as u32);
I guess it's a "position" but it's conflicting with the position later on. This one is client_x and the other is an index in an array. Don't mix variable names like that.

Again, you can write this in one line

2021-04-07 11:43 UTC, cecton commented on yewprint/src/slider.rs
> +                let tick_size = Some(track_size / (self.props.options.len() - 1) as f64);
Write this in one line

2021-04-07 11:44 UTC, cecton commented on yewprint/src/slider.rs
> +    pub value: T,
You did not answer that

2021-04-07 11:45 UTC, cecton commented on yewprint/src/slider.rs
> +    pub options: Vec<(T, Option<String>)>,
You also need to answer that

2021-04-07 11:48 UTC, cecton commented on yewprint-doc/src/slider/example.rs
> +                }
Now try to use `then()` from bool https://doc.rust-lang.org/std/primitive.bool.html#method.then

2021-04-07 13:49 UTC, cecton commented on yewprint/src/slider.rs
> +                let position = (pixel_delta as f64 / tick_size.expect("tick size is None") as f64)
Are you sure this option can ever be None?

2021-04-07 18:33 UTC, cecton commented on yewprint/src/slider.rs
> +                };
Is that if expression?

2021-04-07 19:41 UTC, yozhgoor commented on yewprint/src/slider.rs
> +    pub value: T,
The handle is not rendered, he come back when you click on the slider

2021-04-08 12:32 UTC, cecton approved these changes

2021-04-09 15:47 UTC, merged